<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Lokasi_model extends CI_Model
{

    public $table = 'lokasi';
    public $kd_lokasi = 'kd_lokasi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->kd_lokasi, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by kd_lokasi
    function get_by_kd_lokasi($kd_lokasi)
    {
        $this->db->where($this->kd_lokasi, $kd_lokasi);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('kd_lokasi', $q);
	$this->db->or_like('nm_lokasi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->kd_lokasi, $this->order);
        $this->db->like('kd_lokasi', $q);
	$this->db->or_like('nm_lokasi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($kd_lokasi, $data)
    {
        $this->db->where($this->kd_lokasi, $kd_lokasi);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($kd_lokasi)
    {
        $this->db->where($this->kd_lokasi, $kd_lokasi);
        $this->db->delete($this->table);
    }

}

/* End of file Lokasi_model.php */
/* Location: ./application/models/Lokasi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-24 08:00:42 */
/* http://harviacode.com */